--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 7/12/2020 10:12:39
-- Server version: 5.5.5-10.4.14-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set default database
--
USE bdregistro;

--
-- Drop table `admin`
--
DROP TABLE IF EXISTS admin;

--
-- Drop table `estudiantes`
--
DROP TABLE IF EXISTS estudiantes;

--
-- Set default database
--
USE bdregistro;

--
-- Create table `estudiantes`
--
CREATE TABLE estudiantes (
  id int(11) NOT NULL AUTO_INCREMENT,
  codigo int(11) DEFAULT NULL,
  nombres varchar(100) NOT NULL,
  apellidos varchar(100) NOT NULL,
  genero varchar(100) NOT NULL,
  direccion varchar(100) NOT NULL,
  celular varchar(100) NOT NULL,
  email varchar(100) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 10922,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `admin`
--
CREATE TABLE admin (
  id int(11) NOT NULL AUTO_INCREMENT,
  usuario varchar(255) DEFAULT NULL,
  password varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table estudiantes
--
INSERT INTO estudiantes VALUES
(1, 123456, 'Juan', 'Perez', 'Los perales 254', '999999999', 'juan@hotmail.com', 'M'),
(2, 898989, 'Elena Juana', 'Arismendi', 'Femenino', 'Los rosales', '85874854', 'elena@hotmail.com'),
(3, 252525, 'Joana', 'Tavara', 'Femenino', 'El puerto', '989898', 'joana@hotmail.com'),
(4, 999888, 'Xavier', 'llois', 'Masculino', 'El prado 225', '98959658', 'erere@fdfd.copm');

-- 
-- Dumping data for table admin
--
INSERT INTO admin VALUES
(1, 'admin', '123');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;